// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	internal "go.uber.org/cadence/internal"
)

// ScheduleClient is an autogenerated mock type for the ScheduleClient type
type ScheduleClient struct {
	mock.Mock
}

// Backfill provides a mock function with given fields: ctx, scheduleID, request
func (_m *ScheduleClient) Backfill(ctx context.Context, scheduleID string, request *internal.BackfillRequest) error {
	ret := _m.Called(ctx, scheduleID, request)

	if len(ret) == 0 {
		panic("no return value specified for Backfill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *internal.BackfillRequest) error); ok {
		r0 = rf(ctx, scheduleID, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, request
func (_m *ScheduleClient) Create(ctx context.Context, request *internal.CreateScheduleRequest) (string, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *internal.CreateScheduleRequest) (string, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *internal.CreateScheduleRequest) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *internal.CreateScheduleRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, scheduleID
func (_m *ScheduleClient) Delete(ctx context.Context, scheduleID string) error {
	ret := _m.Called(ctx, scheduleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, scheduleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Describe provides a mock function with given fields: ctx, scheduleID
func (_m *ScheduleClient) Describe(ctx context.Context, scheduleID string) (*internal.DescribeScheduleResponse, error) {
	ret := _m.Called(ctx, scheduleID)

	if len(ret) == 0 {
		panic("no return value specified for Describe")
	}

	var r0 *internal.DescribeScheduleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*internal.DescribeScheduleResponse, error)); ok {
		return rf(ctx, scheduleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *internal.DescribeScheduleResponse); ok {
		r0 = rf(ctx, scheduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.DescribeScheduleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, scheduleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, pageSize, nextPageToken
func (_m *ScheduleClient) List(ctx context.Context, pageSize int32, nextPageToken []byte) (*internal.ListSchedulesResponse, error) {
	ret := _m.Called(ctx, pageSize, nextPageToken)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *internal.ListSchedulesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, []byte) (*internal.ListSchedulesResponse, error)); ok {
		return rf(ctx, pageSize, nextPageToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, []byte) *internal.ListSchedulesResponse); ok {
		r0 = rf(ctx, pageSize, nextPageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal.ListSchedulesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, []byte) error); ok {
		r1 = rf(ctx, pageSize, nextPageToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Pause provides a mock function with given fields: ctx, scheduleID, reason
func (_m *ScheduleClient) Pause(ctx context.Context, scheduleID string, reason string) error {
	ret := _m.Called(ctx, scheduleID, reason)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, scheduleID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unpause provides a mock function with given fields: ctx, scheduleID, reason
func (_m *ScheduleClient) Unpause(ctx context.Context, scheduleID string, reason string) error {
	ret := _m.Called(ctx, scheduleID, reason)

	if len(ret) == 0 {
		panic("no return value specified for Unpause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, scheduleID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, request
func (_m *ScheduleClient) Update(ctx context.Context, request *internal.UpdateScheduleRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *internal.UpdateScheduleRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewScheduleClient creates a new instance of ScheduleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleClient {
	mock := &ScheduleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
