// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence-idl/go/proto/api/v1 (interfaces: ScheduleAPIYARPCClient)

// Package internal is a generated GoMock package.
package internal

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apiv1 "github.com/uber/cadence-idl/go/proto/api/v1"
	yarpc "go.uber.org/yarpc"
)

// MockScheduleAPIYARPCClient is a mock of ScheduleAPIYARPCClient interface.
type MockScheduleAPIYARPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleAPIYARPCClientMockRecorder
}

// MockScheduleAPIYARPCClientMockRecorder is the mock recorder for MockScheduleAPIYARPCClient.
type MockScheduleAPIYARPCClientMockRecorder struct {
	mock *MockScheduleAPIYARPCClient
}

// NewMockScheduleAPIYARPCClient creates a new mock instance.
func NewMockScheduleAPIYARPCClient(ctrl *gomock.Controller) *MockScheduleAPIYARPCClient {
	mock := &MockScheduleAPIYARPCClient{ctrl: ctrl}
	mock.recorder = &MockScheduleAPIYARPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleAPIYARPCClient) EXPECT() *MockScheduleAPIYARPCClientMockRecorder {
	return m.recorder
}

// BackfillSchedule mocks base method.
func (m *MockScheduleAPIYARPCClient) BackfillSchedule(arg0 context.Context, arg1 *apiv1.BackfillScheduleRequest, arg2 ...yarpc.CallOption) (*apiv1.BackfillScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BackfillSchedule", varargs...)
	ret0, _ := ret[0].(*apiv1.BackfillScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackfillSchedule indicates an expected call of BackfillSchedule.
func (mr *MockScheduleAPIYARPCClientMockRecorder) BackfillSchedule(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillSchedule", reflect.TypeOf((*MockScheduleAPIYARPCClient)(nil).BackfillSchedule), varargs...)
}

// CreateSchedule mocks base method.
func (m *MockScheduleAPIYARPCClient) CreateSchedule(arg0 context.Context, arg1 *apiv1.CreateScheduleRequest, arg2 ...yarpc.CallOption) (*apiv1.CreateScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSchedule", varargs...)
	ret0, _ := ret[0].(*apiv1.CreateScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockScheduleAPIYARPCClientMockRecorder) CreateSchedule(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockScheduleAPIYARPCClient)(nil).CreateSchedule), varargs...)
}

// DeleteSchedule mocks base method.
func (m *MockScheduleAPIYARPCClient) DeleteSchedule(arg0 context.Context, arg1 *apiv1.DeleteScheduleRequest, arg2 ...yarpc.CallOption) (*apiv1.DeleteScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteSchedule", varargs...)
	ret0, _ := ret[0].(*apiv1.DeleteScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockScheduleAPIYARPCClientMockRecorder) DeleteSchedule(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockScheduleAPIYARPCClient)(nil).DeleteSchedule), varargs...)
}

// DescribeSchedule mocks base method.
func (m *MockScheduleAPIYARPCClient) DescribeSchedule(arg0 context.Context, arg1 *apiv1.DescribeScheduleRequest, arg2 ...yarpc.CallOption) (*apiv1.DescribeScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeSchedule", varargs...)
	ret0, _ := ret[0].(*apiv1.DescribeScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeSchedule indicates an expected call of DescribeSchedule.
func (mr *MockScheduleAPIYARPCClientMockRecorder) DescribeSchedule(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSchedule", reflect.TypeOf((*MockScheduleAPIYARPCClient)(nil).DescribeSchedule), varargs...)
}

// ListSchedules mocks base method.
func (m *MockScheduleAPIYARPCClient) ListSchedules(arg0 context.Context, arg1 *apiv1.ListSchedulesRequest, arg2 ...yarpc.CallOption) (*apiv1.ListSchedulesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSchedules", varargs...)
	ret0, _ := ret[0].(*apiv1.ListSchedulesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockScheduleAPIYARPCClientMockRecorder) ListSchedules(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockScheduleAPIYARPCClient)(nil).ListSchedules), varargs...)
}

// PauseSchedule mocks base method.
func (m *MockScheduleAPIYARPCClient) PauseSchedule(arg0 context.Context, arg1 *apiv1.PauseScheduleRequest, arg2 ...yarpc.CallOption) (*apiv1.PauseScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PauseSchedule", varargs...)
	ret0, _ := ret[0].(*apiv1.PauseScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseSchedule indicates an expected call of PauseSchedule.
func (mr *MockScheduleAPIYARPCClientMockRecorder) PauseSchedule(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseSchedule", reflect.TypeOf((*MockScheduleAPIYARPCClient)(nil).PauseSchedule), varargs...)
}

// UnpauseSchedule mocks base method.
func (m *MockScheduleAPIYARPCClient) UnpauseSchedule(arg0 context.Context, arg1 *apiv1.UnpauseScheduleRequest, arg2 ...yarpc.CallOption) (*apiv1.UnpauseScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnpauseSchedule", varargs...)
	ret0, _ := ret[0].(*apiv1.UnpauseScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnpauseSchedule indicates an expected call of UnpauseSchedule.
func (mr *MockScheduleAPIYARPCClientMockRecorder) UnpauseSchedule(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpauseSchedule", reflect.TypeOf((*MockScheduleAPIYARPCClient)(nil).UnpauseSchedule), varargs...)
}

// UpdateSchedule mocks base method.
func (m *MockScheduleAPIYARPCClient) UpdateSchedule(arg0 context.Context, arg1 *apiv1.UpdateScheduleRequest, arg2 ...yarpc.CallOption) (*apiv1.UpdateScheduleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateSchedule", varargs...)
	ret0, _ := ret[0].(*apiv1.UpdateScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockScheduleAPIYARPCClientMockRecorder) UpdateSchedule(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockScheduleAPIYARPCClient)(nil).UpdateSchedule), varargs...)
}
