// Code generated by mockery v2.53.3. DO NOT EDIT.

package internal

import (
	context "context"

	apiv1 "github.com/uber/cadence-idl/go/proto/api/v1"

	mock "github.com/stretchr/testify/mock"

	yarpc "go.uber.org/yarpc"
)

// ScheduleAPIYARPCClient is an autogenerated mock type for the ScheduleAPIYARPCClient type
type ScheduleAPIYARPCClient struct {
	mock.Mock
}

type ScheduleAPIYARPCClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ScheduleAPIYARPCClient) EXPECT() *ScheduleAPIYARPCClient_Expecter {
	return &ScheduleAPIYARPCClient_Expecter{mock: &_m.Mock}
}

// BackfillSchedule provides a mock function with given fields: _a0, _a1, _a2
func (_m *ScheduleAPIYARPCClient) BackfillSchedule(_a0 context.Context, _a1 *apiv1.BackfillScheduleRequest, _a2 ...yarpc.CallOption) (*apiv1.BackfillScheduleResponse, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BackfillSchedule")
	}

	var r0 *apiv1.BackfillScheduleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.BackfillScheduleRequest, ...yarpc.CallOption) (*apiv1.BackfillScheduleResponse, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.BackfillScheduleRequest, ...yarpc.CallOption) *apiv1.BackfillScheduleResponse); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.BackfillScheduleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.BackfillScheduleRequest, ...yarpc.CallOption) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleAPIYARPCClient_BackfillSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackfillSchedule'
type ScheduleAPIYARPCClient_BackfillSchedule_Call struct {
	*mock.Call
}

// BackfillSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *apiv1.BackfillScheduleRequest
//   - _a2 ...yarpc.CallOption
func (_e *ScheduleAPIYARPCClient_Expecter) BackfillSchedule(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *ScheduleAPIYARPCClient_BackfillSchedule_Call {
	return &ScheduleAPIYARPCClient_BackfillSchedule_Call{Call: _e.mock.On("BackfillSchedule",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *ScheduleAPIYARPCClient_BackfillSchedule_Call) Run(run func(_a0 context.Context, _a1 *apiv1.BackfillScheduleRequest, _a2 ...yarpc.CallOption)) *ScheduleAPIYARPCClient_BackfillSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]yarpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(yarpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.BackfillScheduleRequest), variadicArgs...)
	})
	return _c
}

func (_c *ScheduleAPIYARPCClient_BackfillSchedule_Call) Return(_a0 *apiv1.BackfillScheduleResponse, _a1 error) *ScheduleAPIYARPCClient_BackfillSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleAPIYARPCClient_BackfillSchedule_Call) RunAndReturn(run func(context.Context, *apiv1.BackfillScheduleRequest, ...yarpc.CallOption) (*apiv1.BackfillScheduleResponse, error)) *ScheduleAPIYARPCClient_BackfillSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSchedule provides a mock function with given fields: _a0, _a1, _a2
func (_m *ScheduleAPIYARPCClient) CreateSchedule(_a0 context.Context, _a1 *apiv1.CreateScheduleRequest, _a2 ...yarpc.CallOption) (*apiv1.CreateScheduleResponse, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 *apiv1.CreateScheduleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.CreateScheduleRequest, ...yarpc.CallOption) (*apiv1.CreateScheduleResponse, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.CreateScheduleRequest, ...yarpc.CallOption) *apiv1.CreateScheduleResponse); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.CreateScheduleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.CreateScheduleRequest, ...yarpc.CallOption) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleAPIYARPCClient_CreateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSchedule'
type ScheduleAPIYARPCClient_CreateSchedule_Call struct {
	*mock.Call
}

// CreateSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *apiv1.CreateScheduleRequest
//   - _a2 ...yarpc.CallOption
func (_e *ScheduleAPIYARPCClient_Expecter) CreateSchedule(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *ScheduleAPIYARPCClient_CreateSchedule_Call {
	return &ScheduleAPIYARPCClient_CreateSchedule_Call{Call: _e.mock.On("CreateSchedule",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *ScheduleAPIYARPCClient_CreateSchedule_Call) Run(run func(_a0 context.Context, _a1 *apiv1.CreateScheduleRequest, _a2 ...yarpc.CallOption)) *ScheduleAPIYARPCClient_CreateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]yarpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(yarpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.CreateScheduleRequest), variadicArgs...)
	})
	return _c
}

func (_c *ScheduleAPIYARPCClient_CreateSchedule_Call) Return(_a0 *apiv1.CreateScheduleResponse, _a1 error) *ScheduleAPIYARPCClient_CreateSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleAPIYARPCClient_CreateSchedule_Call) RunAndReturn(run func(context.Context, *apiv1.CreateScheduleRequest, ...yarpc.CallOption) (*apiv1.CreateScheduleResponse, error)) *ScheduleAPIYARPCClient_CreateSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSchedule provides a mock function with given fields: _a0, _a1, _a2
func (_m *ScheduleAPIYARPCClient) DeleteSchedule(_a0 context.Context, _a1 *apiv1.DeleteScheduleRequest, _a2 ...yarpc.CallOption) (*apiv1.DeleteScheduleResponse, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSchedule")
	}

	var r0 *apiv1.DeleteScheduleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.DeleteScheduleRequest, ...yarpc.CallOption) (*apiv1.DeleteScheduleResponse, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.DeleteScheduleRequest, ...yarpc.CallOption) *apiv1.DeleteScheduleResponse); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.DeleteScheduleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.DeleteScheduleRequest, ...yarpc.CallOption) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleAPIYARPCClient_DeleteSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSchedule'
type ScheduleAPIYARPCClient_DeleteSchedule_Call struct {
	*mock.Call
}

// DeleteSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *apiv1.DeleteScheduleRequest
//   - _a2 ...yarpc.CallOption
func (_e *ScheduleAPIYARPCClient_Expecter) DeleteSchedule(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *ScheduleAPIYARPCClient_DeleteSchedule_Call {
	return &ScheduleAPIYARPCClient_DeleteSchedule_Call{Call: _e.mock.On("DeleteSchedule",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *ScheduleAPIYARPCClient_DeleteSchedule_Call) Run(run func(_a0 context.Context, _a1 *apiv1.DeleteScheduleRequest, _a2 ...yarpc.CallOption)) *ScheduleAPIYARPCClient_DeleteSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]yarpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(yarpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.DeleteScheduleRequest), variadicArgs...)
	})
	return _c
}

func (_c *ScheduleAPIYARPCClient_DeleteSchedule_Call) Return(_a0 *apiv1.DeleteScheduleResponse, _a1 error) *ScheduleAPIYARPCClient_DeleteSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleAPIYARPCClient_DeleteSchedule_Call) RunAndReturn(run func(context.Context, *apiv1.DeleteScheduleRequest, ...yarpc.CallOption) (*apiv1.DeleteScheduleResponse, error)) *ScheduleAPIYARPCClient_DeleteSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeSchedule provides a mock function with given fields: _a0, _a1, _a2
func (_m *ScheduleAPIYARPCClient) DescribeSchedule(_a0 context.Context, _a1 *apiv1.DescribeScheduleRequest, _a2 ...yarpc.CallOption) (*apiv1.DescribeScheduleResponse, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DescribeSchedule")
	}

	var r0 *apiv1.DescribeScheduleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.DescribeScheduleRequest, ...yarpc.CallOption) (*apiv1.DescribeScheduleResponse, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.DescribeScheduleRequest, ...yarpc.CallOption) *apiv1.DescribeScheduleResponse); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.DescribeScheduleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.DescribeScheduleRequest, ...yarpc.CallOption) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleAPIYARPCClient_DescribeSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeSchedule'
type ScheduleAPIYARPCClient_DescribeSchedule_Call struct {
	*mock.Call
}

// DescribeSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *apiv1.DescribeScheduleRequest
//   - _a2 ...yarpc.CallOption
func (_e *ScheduleAPIYARPCClient_Expecter) DescribeSchedule(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *ScheduleAPIYARPCClient_DescribeSchedule_Call {
	return &ScheduleAPIYARPCClient_DescribeSchedule_Call{Call: _e.mock.On("DescribeSchedule",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *ScheduleAPIYARPCClient_DescribeSchedule_Call) Run(run func(_a0 context.Context, _a1 *apiv1.DescribeScheduleRequest, _a2 ...yarpc.CallOption)) *ScheduleAPIYARPCClient_DescribeSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]yarpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(yarpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.DescribeScheduleRequest), variadicArgs...)
	})
	return _c
}

func (_c *ScheduleAPIYARPCClient_DescribeSchedule_Call) Return(_a0 *apiv1.DescribeScheduleResponse, _a1 error) *ScheduleAPIYARPCClient_DescribeSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleAPIYARPCClient_DescribeSchedule_Call) RunAndReturn(run func(context.Context, *apiv1.DescribeScheduleRequest, ...yarpc.CallOption) (*apiv1.DescribeScheduleResponse, error)) *ScheduleAPIYARPCClient_DescribeSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// ListSchedules provides a mock function with given fields: _a0, _a1, _a2
func (_m *ScheduleAPIYARPCClient) ListSchedules(_a0 context.Context, _a1 *apiv1.ListSchedulesRequest, _a2 ...yarpc.CallOption) (*apiv1.ListSchedulesResponse, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListSchedules")
	}

	var r0 *apiv1.ListSchedulesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.ListSchedulesRequest, ...yarpc.CallOption) (*apiv1.ListSchedulesResponse, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.ListSchedulesRequest, ...yarpc.CallOption) *apiv1.ListSchedulesResponse); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ListSchedulesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.ListSchedulesRequest, ...yarpc.CallOption) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleAPIYARPCClient_ListSchedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSchedules'
type ScheduleAPIYARPCClient_ListSchedules_Call struct {
	*mock.Call
}

// ListSchedules is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *apiv1.ListSchedulesRequest
//   - _a2 ...yarpc.CallOption
func (_e *ScheduleAPIYARPCClient_Expecter) ListSchedules(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *ScheduleAPIYARPCClient_ListSchedules_Call {
	return &ScheduleAPIYARPCClient_ListSchedules_Call{Call: _e.mock.On("ListSchedules",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *ScheduleAPIYARPCClient_ListSchedules_Call) Run(run func(_a0 context.Context, _a1 *apiv1.ListSchedulesRequest, _a2 ...yarpc.CallOption)) *ScheduleAPIYARPCClient_ListSchedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]yarpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(yarpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.ListSchedulesRequest), variadicArgs...)
	})
	return _c
}

func (_c *ScheduleAPIYARPCClient_ListSchedules_Call) Return(_a0 *apiv1.ListSchedulesResponse, _a1 error) *ScheduleAPIYARPCClient_ListSchedules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleAPIYARPCClient_ListSchedules_Call) RunAndReturn(run func(context.Context, *apiv1.ListSchedulesRequest, ...yarpc.CallOption) (*apiv1.ListSchedulesResponse, error)) *ScheduleAPIYARPCClient_ListSchedules_Call {
	_c.Call.Return(run)
	return _c
}

// PauseSchedule provides a mock function with given fields: _a0, _a1, _a2
func (_m *ScheduleAPIYARPCClient) PauseSchedule(_a0 context.Context, _a1 *apiv1.PauseScheduleRequest, _a2 ...yarpc.CallOption) (*apiv1.PauseScheduleResponse, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PauseSchedule")
	}

	var r0 *apiv1.PauseScheduleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.PauseScheduleRequest, ...yarpc.CallOption) (*apiv1.PauseScheduleResponse, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.PauseScheduleRequest, ...yarpc.CallOption) *apiv1.PauseScheduleResponse); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.PauseScheduleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.PauseScheduleRequest, ...yarpc.CallOption) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleAPIYARPCClient_PauseSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseSchedule'
type ScheduleAPIYARPCClient_PauseSchedule_Call struct {
	*mock.Call
}

// PauseSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *apiv1.PauseScheduleRequest
//   - _a2 ...yarpc.CallOption
func (_e *ScheduleAPIYARPCClient_Expecter) PauseSchedule(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *ScheduleAPIYARPCClient_PauseSchedule_Call {
	return &ScheduleAPIYARPCClient_PauseSchedule_Call{Call: _e.mock.On("PauseSchedule",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *ScheduleAPIYARPCClient_PauseSchedule_Call) Run(run func(_a0 context.Context, _a1 *apiv1.PauseScheduleRequest, _a2 ...yarpc.CallOption)) *ScheduleAPIYARPCClient_PauseSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]yarpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(yarpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.PauseScheduleRequest), variadicArgs...)
	})
	return _c
}

func (_c *ScheduleAPIYARPCClient_PauseSchedule_Call) Return(_a0 *apiv1.PauseScheduleResponse, _a1 error) *ScheduleAPIYARPCClient_PauseSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleAPIYARPCClient_PauseSchedule_Call) RunAndReturn(run func(context.Context, *apiv1.PauseScheduleRequest, ...yarpc.CallOption) (*apiv1.PauseScheduleResponse, error)) *ScheduleAPIYARPCClient_PauseSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// UnpauseSchedule provides a mock function with given fields: _a0, _a1, _a2
func (_m *ScheduleAPIYARPCClient) UnpauseSchedule(_a0 context.Context, _a1 *apiv1.UnpauseScheduleRequest, _a2 ...yarpc.CallOption) (*apiv1.UnpauseScheduleResponse, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UnpauseSchedule")
	}

	var r0 *apiv1.UnpauseScheduleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.UnpauseScheduleRequest, ...yarpc.CallOption) (*apiv1.UnpauseScheduleResponse, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.UnpauseScheduleRequest, ...yarpc.CallOption) *apiv1.UnpauseScheduleResponse); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.UnpauseScheduleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.UnpauseScheduleRequest, ...yarpc.CallOption) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleAPIYARPCClient_UnpauseSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpauseSchedule'
type ScheduleAPIYARPCClient_UnpauseSchedule_Call struct {
	*mock.Call
}

// UnpauseSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *apiv1.UnpauseScheduleRequest
//   - _a2 ...yarpc.CallOption
func (_e *ScheduleAPIYARPCClient_Expecter) UnpauseSchedule(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *ScheduleAPIYARPCClient_UnpauseSchedule_Call {
	return &ScheduleAPIYARPCClient_UnpauseSchedule_Call{Call: _e.mock.On("UnpauseSchedule",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *ScheduleAPIYARPCClient_UnpauseSchedule_Call) Run(run func(_a0 context.Context, _a1 *apiv1.UnpauseScheduleRequest, _a2 ...yarpc.CallOption)) *ScheduleAPIYARPCClient_UnpauseSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]yarpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(yarpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.UnpauseScheduleRequest), variadicArgs...)
	})
	return _c
}

func (_c *ScheduleAPIYARPCClient_UnpauseSchedule_Call) Return(_a0 *apiv1.UnpauseScheduleResponse, _a1 error) *ScheduleAPIYARPCClient_UnpauseSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleAPIYARPCClient_UnpauseSchedule_Call) RunAndReturn(run func(context.Context, *apiv1.UnpauseScheduleRequest, ...yarpc.CallOption) (*apiv1.UnpauseScheduleResponse, error)) *ScheduleAPIYARPCClient_UnpauseSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSchedule provides a mock function with given fields: _a0, _a1, _a2
func (_m *ScheduleAPIYARPCClient) UpdateSchedule(_a0 context.Context, _a1 *apiv1.UpdateScheduleRequest, _a2 ...yarpc.CallOption) (*apiv1.UpdateScheduleResponse, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSchedule")
	}

	var r0 *apiv1.UpdateScheduleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.UpdateScheduleRequest, ...yarpc.CallOption) (*apiv1.UpdateScheduleResponse, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *apiv1.UpdateScheduleRequest, ...yarpc.CallOption) *apiv1.UpdateScheduleResponse); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.UpdateScheduleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *apiv1.UpdateScheduleRequest, ...yarpc.CallOption) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleAPIYARPCClient_UpdateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSchedule'
type ScheduleAPIYARPCClient_UpdateSchedule_Call struct {
	*mock.Call
}

// UpdateSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *apiv1.UpdateScheduleRequest
//   - _a2 ...yarpc.CallOption
func (_e *ScheduleAPIYARPCClient_Expecter) UpdateSchedule(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *ScheduleAPIYARPCClient_UpdateSchedule_Call {
	return &ScheduleAPIYARPCClient_UpdateSchedule_Call{Call: _e.mock.On("UpdateSchedule",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *ScheduleAPIYARPCClient_UpdateSchedule_Call) Run(run func(_a0 context.Context, _a1 *apiv1.UpdateScheduleRequest, _a2 ...yarpc.CallOption)) *ScheduleAPIYARPCClient_UpdateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]yarpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(yarpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*apiv1.UpdateScheduleRequest), variadicArgs...)
	})
	return _c
}

func (_c *ScheduleAPIYARPCClient_UpdateSchedule_Call) Return(_a0 *apiv1.UpdateScheduleResponse, _a1 error) *ScheduleAPIYARPCClient_UpdateSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleAPIYARPCClient_UpdateSchedule_Call) RunAndReturn(run func(context.Context, *apiv1.UpdateScheduleRequest, ...yarpc.CallOption) (*apiv1.UpdateScheduleResponse, error)) *ScheduleAPIYARPCClient_UpdateSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// NewScheduleAPIYARPCClient creates a new instance of ScheduleAPIYARPCClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleAPIYARPCClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleAPIYARPCClient {
	mock := &ScheduleAPIYARPCClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
