version: "3.5"

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    networks:
      services-network:
        aliases:
          - cassandra

  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "8080:80"
      - "2003:2003"
      - "8125:8125"
      - "8126:8126"
    networks:
      services-network:
        aliases:
          - statsd

  cadence:
    image: ubercadence/server:master
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "STATSD_ENDPOINT=statsd:8125"
    depends_on:
      - cassandra
      - statsd
    networks:
      services-network:
        aliases:
          - cadence

  integ-test:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    environment:
      - "SERVICE_ADDR=cadence:7933"
    depends_on:
      - cadence
    volumes:
      - ../../:/go/src/go.uber.org/cadence
    networks:
      services-network:
        aliases:
          - integ-test

  unit-test:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    volumes:
      - ../../:/go/src/go.uber.org/cadence
    networks:
      services-network:
        aliases:
          - unit-test

  coverage-report:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    environment:
      - BUILDKITE_BUILD_ID
    volumes:
      - ../../:/go/src/go.uber.org/cadence
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent

networks:
  services-network:
    name: services-network
    driver: bridge